CameraClick:

<CameraClick>
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (self.width, self.height)
        play: False
        keep_ratio: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()